<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{{ $title }} - {{ $store->name }}</title>
    <style>
        /* Same base styles as above */
        body {
            font-family: Arial, sans-serif;
            font-size: 12px;
            line-height: 1.4;
            color: #333;
        }

        .header {
            text-align: center;
            margin-bottom: 30px;
            border-bottom: 2px solid #4f46e5;
            padding-bottom: 20px;
        }

        .header h1 {
            margin: 0;
            color: #4f46e5;
            font-size: 24px;
        }

        .header .store-info {
            margin-top: 10px;
            color: #666;
        }

        .metrics {
            display: flex;
            justify-content: space-around;
            margin: 20px 0;
            background: #f8fafc;
            padding: 15px;
            border-radius: 8px;
        }

        .metric {
            text-align: center;
        }

        .metric-value {
            font-size: 20px;
            font-weight: bold;
            color: #4f46e5;
        }

        .metric-label {
            color: #666;
            margin-top: 5px;
        }

        .table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }

        .table th,
        .table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }

        .table th {
            background-color: #f8fafc;
            font-weight: bold;
        }

        .table tr:nth-child(even) {
            background-color: #f9f9f9;
        }

        .footer {
            margin-top: 30px;
            text-align: center;
            color: #666;
            font-size: 10px;
            border-top: 1px solid #ddd;
            padding-top: 15px;
        }

        .section-title {
            font-size: 16px;
            font-weight: bold;
            margin: 25px 0 15px 0;
            color: #374151;
            border-bottom: 1px solid #e5e7eb;
            padding-bottom: 5px;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ $title }}</h1>
        <div class="store-info">
            <strong>Store:</strong> {{ $store->name }}<br>
            <strong>Period:</strong> {{ $date_range['start'] }} to {{ $date_range['end'] }}<br>
            <strong>Generated:</strong> {{ $generated_at }}
        </div>
    </div>

    <div class="metrics">
        <div class="metric">
            <div class="metric-value">${{ number_format($data['metrics']['total_sales'], 2) }}</div>
            <div class="metric-label">Total Sales</div>
        </div>
        <div class="metric">
            <div class="metric-value">{{ number_format($data['metrics']['total_products']) }}</div>
            <div class="metric-label">Total Products</div>
        </div>
        <div class="metric">
            <div class="metric-value">{{ number_format($data['metrics']['active_products']) }}</div>
            <div class="metric-label">Active Products</div>
        </div>
    </div>

    @if(!empty($data['products']))
    <div class="section-title">Top Performing Products</div>
    <table class="table">
        <thead>
            <tr>
                <th>Product</th>
                <th>Vendor</th>
                <th>Revenue</th>
                <th>Quantity Sold</th>
                <th>Orders</th>
            </tr>
        </thead>
        <tbody>
            @foreach(array_slice($data['products'], 0, 15) as $product)
            <tr>
                <td>{{ $product['title'] }}</td>
                <td>{{ $product['vendor'] }}</td>
                <td>${{ number_format($product['total_sales'], 2) }}</td>
                <td>{{ number_format($product['total_quantity']) }}</td>
                <td>{{ number_format($product['orders_count']) }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>
    @endif

    <div class="footer">
        Report generated by {{ config('app.name') }} on {{ $generated_at }}
    </div>
</body>

</html>